// Original English question bank. sourceTags document the teaching approach,
// not the source of an exercise; no questions are copied from the papers.
// Equivalence: https://link.springer.com/article/10.1186/s40594-019-0183-2
// Compact inverse steps: https://doi.org/10.1080/01443410.2013.878019
// Comparing methods: https://doi.org/10.1037/a0014224
// Powers/logs: https://files.eric.ed.gov/fulltext/ED477690.pdf
// Meaning and domains: https://files.eric.ed.gov/fulltext/EJ1093384.pdf
// Error analysis: https://math.nie.edu.sg/ame/matheduc/tme/tmeV8_2/Final%20Chua%20Wood.pdf
const math = String.raw;
const choices = (...texts) => texts.map((text, index) => ({ id: 'abcd'[index], text }));
const published = question => ({ ...question, published: true });

export const questions = [
  {
    id: 'eq-01', topic: 'equations', difficulty: 1,
    prompt: 'Which value makes both sides equal?', math: math`9+6=x+7`,
    options: choices('x = 15', 'x = 8', 'x = 22', 'x = 2'), correctOptionId: 'b',
    hint: 'Both sides must have the same value. The left side is 15.',
    explanation: ['The left side equals 15, so x + 7 must also equal 15.', 'Subtract 7 from both sides: x = 15 − 7 = 8.', 'Check: 9 + 6 = 8 + 7 = 15.'],
    misconception: 'The equals sign describes a relationship. It does not say to put the left-hand total immediately after it.',
    sourceTags: ['otten'],
  },
  {
    id: 'eq-02', topic: 'equations', difficulty: 1,
    prompt: 'Solve for x.', math: math`x+7=12`,
    options: choices('x = 5', 'x = 19', 'x = −5', 'x = 12/7'), correctOptionId: 'a',
    hint: 'Which operation undoes adding 7?',
    explanation: ['Subtract 7 from both sides.', 'x = 12 − 7 = 5.', 'Check: 5 + 7 = 12.'],
    misconception: 'Undo +7 with −7. The change of sign in a short solution comes from that subtraction.',
    sourceTags: ['ngu', 'otten'],
  },
  {
    id: 'eq-03', topic: 'equations', difficulty: 1,
    prompt: 'Solve for x.', math: math`x-9=-2`,
    options: choices('x = −11', 'x = 11', 'x = −7', 'x = 7'), correctOptionId: 'd',
    hint: 'Add 9 to both sides to undo subtracting 9.',
    explanation: ['x − 9 + 9 = −2 + 9.', 'Therefore x = 7.', 'Check: 7 − 9 = −2.'],
    misconception: 'A negative number on the right does not mean the solution must be negative.',
    sourceTags: ['ngu'],
  },
  {
    id: 'eq-04', topic: 'equations', difficulty: 1,
    prompt: 'Solve for x.', math: math`-4x=20`,
    options: choices('x = 5', 'x = −80', 'x = −5', 'x = 16'), correctOptionId: 'c',
    hint: 'Divide both sides by the complete coefficient of x, including its sign.',
    explanation: ['The coefficient of x is −4.', 'Divide both sides by −4: x = 20/(−4) = −5.', 'Check: (−4) × (−5) = 20.'],
    misconception: 'The minus sign is part of the coefficient. Dividing by 4 instead would leave −x, not x.',
    sourceTags: ['ngu'],
  },
  {
    id: 'eq-05', topic: 'equations', difficulty: 1,
    prompt: 'Solve for x.', math: math`\frac{x}{3}+2=7`,
    options: choices('x = 5/3', 'x = 15', 'x = 9', 'x = 27'), correctOptionId: 'b',
    hint: 'Undo the addition first, then undo the division.',
    explanation: ['Subtract 2 from both sides: x/3 = 5.', 'Multiply both sides by 3: x = 15.', 'Check: 15/3 + 2 = 7.'],
    misconception: 'Division by 3 is undone by multiplication by 3, not by another division.',
    sourceTags: ['ngu'],
  },
  {
    id: 'eq-06', topic: 'equations', difficulty: 1,
    prompt: 'Solve for x.', math: math`3x+5=20`,
    options: choices('x = 25/3', 'x = 15', 'x = 20/3 − 5', 'x = 5'), correctOptionId: 'd',
    hint: 'First undo adding 5. Then undo multiplying by 3.',
    explanation: ['Subtract 5 from both sides: 3x = 15.', 'Divide both sides by 3: x = 5.', 'Check: 3 × 5 + 5 = 20.'],
    misconception: 'If you divide a whole sum by 3, every term must be divided. Subtracting 5 first is simpler here.',
    sourceTags: ['otten', 'ngu'],
  },
  {
    id: 'eq-07', topic: 'equations', difficulty: 2,
    prompt: 'Solve an equation with x on both sides.', math: math`3x+5=x+13`,
    options: choices('x = 4', 'x = 9', 'x = 2', 'x = −4'), correctOptionId: 'a',
    hint: 'Subtract x from both sides to collect the unknown terms.',
    explanation: ['Subtract x: 2x + 5 = 13.', 'Subtract 5: 2x = 8.', 'Divide by 2: x = 4.', 'Check: both original sides equal 17.'],
    misconception: 'Terms on opposite sides cannot simply be combined; first perform an operation that preserves equality.',
    sourceTags: ['otten', 'ngu'],
  },
  {
    id: 'eq-08', topic: 'equations', difficulty: 2,
    prompt: 'Solve for x. You may choose either a valid expansion or an inverse operation.', math: math`2(x+3)=18`,
    options: choices('x = 12', 'x = 7.5', 'x = 6', 'x = 9'), correctOptionId: 'c',
    hint: 'Dividing both sides by 2 avoids expanding the brackets.',
    explanation: ['Divide by 2: x + 3 = 9. Subtract 3: x = 6.', 'Another valid route is 2x + 6 = 18, then 2x = 12, then x = 6.', 'Both routes preserve equality. Check: 2(6 + 3) = 18.'],
    misconception: 'When expanding brackets, the outside factor multiplies every term inside.',
    sourceTags: ['rittle', 'ngu'],
  },
  {
    id: 'eq-09', topic: 'equations', difficulty: 2,
    prompt: 'Solve for x.', math: math`\frac{x-2}{4}=3`,
    options: choices('x = 10', 'x = 14', 'x = 2.75', 'x = 20'), correctOptionId: 'b',
    hint: 'The entire numerator x − 2 is divided by 4.',
    explanation: ['Multiply both sides by 4: x − 2 = 12.', 'Add 2 to both sides: x = 14.', 'Check: (14 − 2)/4 = 3.'],
    misconception: 'The fraction bar groups the whole numerator. Do not apply it only to x.',
    sourceTags: ['ngu'],
  },
  {
    id: 'eq-10', topic: 'equations', difficulty: 2,
    prompt: 'Solve for x.', math: math`\frac{x}{2}+\frac{x}{3}=10`,
    options: choices('x = 50', 'x = 10', 'x = 12', 'x = 5'), correctOptionId: 'c',
    hint: 'Multiply every term on both sides by the common denominator 6.',
    explanation: ['Multiplying by 6 gives 3x + 2x = 60.', 'Combine like terms: 5x = 60, so x = 12.', 'Check: 12/2 + 12/3 = 6 + 4 = 10.'],
    misconception: 'Adding fractions does not mean adding their denominators. Use a common denominator or multiply the entire equation.',
    sourceTags: ['ngu', 'otten'],
  },
  {
    id: 'eq-11', topic: 'equations', difficulty: 2,
    prompt: 'Which real numbers satisfy this equation?', math: math`2(x+3)=2x+6`,
    options: choices('Only x = 0', 'No real numbers', 'Only x = 3', 'Every real number'), correctOptionId: 'd',
    hint: 'Expand the left side and compare the expressions.',
    explanation: ['The left side expands to 2x + 6.', 'Both sides are the same expression for every real x.', 'The solution set is all real numbers.'],
    misconception: 'When x disappears, it does not automatically follow that x = 0. Decide whether the remaining statement is true.',
    sourceTags: ['otten'],
  },
  {
    id: 'eq-12', topic: 'equations', difficulty: 2,
    prompt: 'Which real numbers satisfy this equation?', math: math`4x+1=4x+7`,
    options: choices('No real numbers', 'Every real number', 'Only x = 6', 'Only x = 0'), correctOptionId: 'a',
    hint: 'Subtract 4x from both sides.',
    explanation: ['Subtracting 4x gives 1 = 7.', 'That statement is false regardless of x.', 'The equation has no solution.'],
    misconception: 'When variable terms cancel, a false equality means no solution, not infinitely many solutions.',
    sourceTags: ['otten'],
  },
  {
    id: 'eq-13', topic: 'equations', difficulty: 2,
    prompt: 'Why is the displayed expansion incorrect?', math: math`2(x+3)=14\quad\Rightarrow\quad 2x+3=14`,
    options: choices('2 cannot multiply x', '2 must also multiply 3', 'Equations cannot contain brackets', 'The expansion is correct'), correctOptionId: 'b',
    hint: 'Use the distributive property: a(b + c) = ab + ac.',
    explanation: ['The correct expansion is 2(x + 3) = 2x + 6.', 'The equation becomes 2x + 6 = 14.', 'Subtract 6 and divide by 2 to obtain x = 4.'],
    misconception: 'The outside factor multiplies every term. Changing only one term changes the value of the expression.',
    sourceTags: ['otten'],
  },
  {
    id: 'eq-14', topic: 'equations', difficulty: 2,
    prompt: 'Alex expands the brackets. Sam first divides both sides by 3. Who starts with a valid method?', math: math`3(x+2)=18`,
    options: choices('Only Alex', 'Only Sam', 'Neither', 'Both'), correctOptionId: 'd',
    hint: 'Check whether each transformation preserves the equality.',
    explanation: ['Alex: 3x + 6 = 18, then 3x = 12, then x = 4.', 'Sam: x + 2 = 6, then x = 4.', 'Both methods work. Dividing first needs fewer calculations in this example.'],
    misconception: 'A problem can have several correct solution methods. Flexibility means choosing one that suits its structure.',
    sourceTags: ['rittle'],
  },
  {
    id: 'log-01', topic: 'logarithms', difficulty: 1,
    prompt: 'Evaluate the logarithm.', math: math`\log_2(8)`,
    options: choices('3', '4', '6', '16'), correctOptionId: 'a',
    hint: 'What power of 2 gives 8?',
    explanation: ['2 raised to the power 3 equals 8.', 'By definition, log₂(8) = 3.'],
    misconception: 'A logarithm is not the argument divided by the base. It asks for an exponent.',
    sourceTags: ['weber'],
  },
  {
    id: 'log-02', topic: 'logarithms', difficulty: 1,
    prompt: 'Solve for x.', math: math`\log_3(x)=2`,
    options: choices('x = 6', 'x = 8', 'x = 9', 'x = 2/3'), correctOptionId: 'c',
    hint: 'Express the same relationship using a power.',
    explanation: ['The domain requires x > 0.', 'The logarithmic equation means x = 3² = 9.', '9 is positive, so it is a valid solution.'],
    misconception: 'The logarithm value is an exponent. Do not multiply the base by it.',
    sourceTags: ['weber', 'kenney'],
  },
  {
    id: 'log-03', topic: 'logarithms', difficulty: 1,
    prompt: 'Which exponential statement expresses the same relationship?', math: math`\log_5(25)=2`,
    options: choices('2⁵ = 25', '5² = 25', '25² = 5', '5 × 2 = 25'), correctOptionId: 'b',
    hint: 'The logarithm base stays the base of the power.',
    explanation: [math`The definition is $\log_b(a)=c\iff b^c=a$.`, 'Here the base is 5, the argument is 25, and the exponent is 2.', 'Therefore 5² = 25.'],
    misconception: 'Keep the base, argument, and exponent in their proper roles when changing representations.',
    sourceTags: ['weber'],
  },
  {
    id: 'log-04', topic: 'logarithms', difficulty: 1,
    prompt: 'Evaluate the logarithm.', math: math`\log_{10}(0.01)`,
    options: choices('2', '0.1', '−0.01', '−2'), correctOptionId: 'd',
    hint: 'Write 0.01 as a power of 10.',
    explanation: ['0.01 = 1/100 = 10⁻².', 'Therefore log₁₀(0.01) = −2.', 'The argument is positive even though the answer is negative.'],
    misconception: 'A real logarithm needs a positive argument, but its value can be negative.',
    sourceTags: ['weber', 'kenney'],
  },
  {
    id: 'log-05', topic: 'logarithms', difficulty: 1,
    prompt: 'For which real values of x is this expression defined?', math: math`\log_2(x-3)`,
    options: choices('x ≥ 3', 'x > 0', 'x > 3', 'x ≠ 3'), correctOptionId: 'c',
    hint: 'The argument of a real logarithm must be strictly positive.',
    explanation: ['Require x − 3 > 0.', 'Adding 3 gives x > 3.', 'At x = 3 the argument is zero, so it is excluded.'],
    misconception: 'Excluding zero alone is not enough: negative arguments are excluded too.',
    sourceTags: ['kenney'],
  },
  {
    id: 'log-06', topic: 'logarithms', difficulty: 1,
    prompt: 'Which number can be the base of a real logarithm?',
    options: choices('1/2', '−2', '0', '1'), correctOptionId: 'a',
    hint: 'A real logarithm has base b > 0 with b ≠ 1.',
    explanation: ['1/2 is positive and different from 1.', 'Bases between 0 and 1 are permitted.', '−2, 0, and 1 do not meet the conditions.'],
    misconception: 'A logarithm base does not have to be greater than 1; it must be positive and not equal to 1.',
    sourceTags: ['kenney'],
  },
  {
    id: 'log-07', topic: 'logarithms', difficulty: 1,
    prompt: 'Solve for x.', math: math`\ln(x)=2`,
    options: choices('x = 2e', 'x = 2', 'x = ln(2)', 'x = e²'), correctOptionId: 'd',
    hint: 'ln is the logarithm with base e. Its inverse is exponentiation with base e.',
    explanation: ['The domain is x > 0.', math`Apply the exponential function to both sides: $e^{\ln(x)}=e^2$.`, 'Therefore x = e², which is positive.'],
    misconception: 'Do not divide by the symbol ln. Apply its inverse function.',
    sourceTags: ['kenney', 'weber'],
  },
  {
    id: 'log-08', topic: 'logarithms', difficulty: 2,
    prompt: 'Solve for x.', math: math`\ln(x-2)=3`,
    options: choices('x = e³ − 2', 'x = e³ + 2', 'x = 5', 'x = e⁵'), correctOptionId: 'b',
    hint: 'State the domain before undoing the logarithm.',
    explanation: ['Require x − 2 > 0, so x > 2.', 'Exponentiate both sides: x − 2 = e³.', 'Add 2: x = e³ + 2.', 'This is greater than 2, so the original logarithm is defined.'],
    misconception: 'The 2 is added after exponentiation. It does not become part of the exponent.',
    sourceTags: ['kenney', 'ngu'],
  },
  {
    id: 'log-09', topic: 'logarithms', difficulty: 3,
    prompt: 'Find the real solution set.', math: math`\log_2(x)+\log_2(x-2)=3`,
    options: choices('Only x = 4', 'Only x = −2', 'x = −2 or x = 4', 'Only x = 5'), correctOptionId: 'a',
    hint: 'The domain is x > 2. A sum of logarithms with the same base is the logarithm of a product.',
    explanation: ['Both arguments must be positive: x > 0 and x − 2 > 0, giving x > 2.', math`Combine: $\log_2(x(x-2))=3$, so $x(x-2)=8$.`, math`Rearrange and factor: $x^2-2x-8=(x-4)(x+2)=0$.`, 'The algebraic candidates are 4 and −2. Only 4 satisfies x > 2.', 'Check: log₂(4) + log₂(2) = 2 + 1 = 3.'],
    misconception: 'A candidate from a transformed equation is not a solution until it satisfies the original domain.',
    sourceTags: ['kenney', 'chua'],
  },
  {
    id: 'log-10', topic: 'logarithms', difficulty: 3,
    prompt: 'Solve for x.', math: math`\log_2(x+1)-\log_2(x-1)=1`,
    options: choices('x = 1', 'x = 2', 'x = 3', 'x = −3'), correctOptionId: 'c',
    hint: 'Use x > 1 and the logarithm quotient rule.',
    explanation: ['The two positive-argument conditions give x > 1.', math`Combine: $\log_2\left(\frac{x+1}{x-1}\right)=1$, so $\frac{x+1}{x-1}=2$.`, 'Since x − 1 is nonzero in the domain, multiply by it: x + 1 = 2x − 2.', 'Solve to obtain x = 3, which is in the domain.', 'Check: log₂(4) − log₂(2) = 2 − 1 = 1.'],
    misconception: 'Subtracting logarithms gives the logarithm of a quotient, not the logarithm of a difference.',
    sourceTags: ['kenney', 'chua'],
  },
  {
    id: 'log-11', topic: 'logarithms', difficulty: 2,
    prompt: 'Solve for x.', math: math`\log_2(x-1)=\log_2(5-x)`,
    options: choices('x = 2', 'x = 4', 'x = 5', 'x = 3'), correctOptionId: 'd',
    hint: 'Establish the domain. Equal logarithms with the same valid base have equal arguments.',
    explanation: ['Require x − 1 > 0 and 5 − x > 0, giving 1 < x < 5.', 'The logarithm function is one-to-one, so x − 1 = 5 − x.', 'Then 2x = 6 and x = 3.', '3 lies in the domain; both logarithms equal log₂(2) = 1.'],
    misconception: 'The arguments are equal because the function is one-to-one, not because log is a common factor.',
    sourceTags: ['kenney'],
  },
  {
    id: 'log-12', topic: 'logarithms', difficulty: 3,
    prompt: 'Solve for x.', math: math`\log_2(x+2)=\log_2(x)+1`,
    options: choices('x = 1', 'x = 2', 'x = 3', 'x = 4'), correctOptionId: 'b',
    hint: 'The domain is x > 0. Rewrite 1 as log₂(2).',
    explanation: ['The original logarithms require x > 0.', math`Rewrite the right side: $\log_2(x)+\log_2(2)=\log_2(2x)$.`, 'Equal logarithms of the same base have equal arguments: x + 2 = 2x.', 'Thus x = 2, which satisfies the domain.', 'Check: log₂(4) = log₂(2) + 1 = 2.'],
    misconception: 'log₂(x) + 1 is not log₂(x + 1). Write the constant as a logarithm before using a log rule.',
    sourceTags: ['chua', 'kenney'],
  },
  {
    id: 'log-13', topic: 'logarithms', difficulty: 2,
    prompt: 'Evaluate the expression without inventing a rule for sums.', math: math`\log_2(8+8)`,
    options: choices('4', '6', '9', '16'), correctOptionId: 'a',
    hint: 'Calculate the argument first.',
    explanation: ['The argument is 8 + 8 = 16.', 'Since 2⁴ = 16, log₂(16) = 4.', 'By contrast, log₂(8) + log₂(8) = 6. This is a different expression.'],
    misconception: 'The logarithm of a sum is not, in general, the sum of the logarithms.',
    sourceTags: ['chua'],
  },
  {
    id: 'log-14', topic: 'logarithms', difficulty: 3,
    prompt: 'Choose the exact solution.', math: math`2^{x+1}=7`,
    options: choices('x = log₂(7) + 1', 'x = log₂(7)/2', 'x = log₂(7) − 1', 'x = 7/2 − 1'), correctOptionId: 'c',
    hint: 'Apply the logarithm with base 2 to both sides.',
    explanation: [math`Apply $\log_2$: $x+1=\log_2(7)$.`, math`Subtract 1: $x=\log_2(7)-1$.`, 'The approximate value is 1.807. The logarithmic expression is exact.', math`Check: $2^{x+1}=2^{\log_2(7)}=7$.`],
    misconception: 'An unknown exponent is isolated using a logarithm, not by dividing the result by the base.',
    sourceTags: ['weber', 'kenney'],
  },
].map(published);
