import { useState } from 'react';
import { ArrowLeft, ArrowRight, Check, CheckCircle2, Clock3, Lightbulb, PencilLine } from 'lucide-react';
import type { Lesson, Source, Topic } from './types';
import { MathText, RichText, SourcesNote } from './components';
import { useLanguage } from './i18n';
import { LessonVisual } from './LessonVisual';
import { VocabularyHint, WordPreview } from './Vocabulary';

export function Lessons({ topic, lessons, sources, selectedId, completed, onComplete }: { topic: Topic; lessons: Lesson[]; sources: Source[]; selectedId?: string; completed: string[]; onComplete: (id: string) => void }) {
  const { language } = useLanguage();
  const say = (nl: string, en: string) => language === 'nl' ? nl : en;
  const lesson = lessons.find(item => item.id === selectedId) || lessons[0];
  const currentIndex = lessons.findIndex(item => item.id === lesson?.id);
  if (!lesson) return <section className="empty-state"><h1>{say('De lessen komen eraan.', 'Lessons are on their way.')}</h1><p>{say('Er zijn nog geen lessen over dit onderwerp. Je kunt de andere onderdelen bekijken.', 'There are no published lessons in this topic yet. You can explore the other phases.')}</p><a href="#home" className="button secondary">{say('Terug naar je leerroute', 'Back to your learning path')}</a></section>;
  return <>
    <div className="page-heading lesson-heading"><span className="eyebrow">{say('FASE', 'PHASE')} {topic === 'equations' ? '01' : '02'} / {say('BEGRIJP HET IDEE', 'LEARN THE IDEA')}</span><h1>{topic === 'equations' ? say('Welk getal is x?', 'What number is x?') : say('Hoe vaak vermenigvuldig je?', 'How many times do you multiply?')}</h1><p>{topic === 'equations' ? say('Begin met wat je al kunt: rekenen. Daarna leer je stap voor stap hoe je een onbekend getal vindt.', 'Start with what you already know: arithmetic. Then learn, step by step, how to find a missing number.') : say('Eerst bekijk je machten, zoals 2³ = 8. Daarna draai je de vraag om: welke macht heb je nodig?', 'First explore powers, such as 2³ = 8. Then turn the question around: which power do you need?')}</p></div>
    <nav className="lesson-tabs" aria-label={say('Lessen over ' + (topic === 'equations' ? 'vergelijkingen' : 'logaritmen'), `${topic} lessons`)}>{lessons.map((item, index) => <a className={`lesson-tab ${item.id === lesson.id ? 'active' : ''}`} href={`#${topic}/${item.id}`} key={item.id} aria-current={item.id === lesson.id ? 'step' : undefined}><span>{completed.includes(item.id) ? <Check size={14} aria-label={say('Afgerond', 'Completed')} /> : String(index + 1).padStart(2, '0')}</span><div>{item.title}<small>{item.minutes} min</small></div></a>)}</nav>
    <LessonReader key={lesson.id} lesson={lesson} sources={sources} index={currentIndex} count={lessons.length} completed={completed.includes(lesson.id)} onComplete={() => onComplete(lesson.id)} next={lessons[currentIndex + 1]} />
  </>;
}

function LessonReader({ lesson, sources, index, count, completed, onComplete, next }: { lesson: Lesson; sources: Source[]; index: number; count: number; completed: boolean; onComplete: () => void; next?: Lesson }) {
  const { language } = useLanguage();
  const say = (nl: string, en: string) => language === 'nl' ? nl : en;
  const [selected, setSelected] = useState<number | null>(null);
  const [checked, setChecked] = useState(false);
  const correct = selected === lesson.checkpoint.correct;
  const canComplete = checked && correct;
  const nextHref = next ? `#${next.topic}/${next.id}` : lesson.topic === 'equations' ? '#logarithms' : '#practice';
  return <article className="lesson-reader">
    <header className="reader-header"><div className="reader-meta"><span>{say('LES', 'LESSON')} {index + 1} {say('VAN', 'OF')} {count}</span><span><Clock3 size={13} /> {lesson.minutes} {say('min lezen', 'min read')}</span>{completed && <span className="completed-label"><CheckCircle2 size={14} /> {say('Afgerond', 'Completed')}</span>}</div><h2>{lesson.title}</h2><p><RichText text={lesson.summary} definitions /></p></header>
    <VocabularyHint />
    {lesson.sections.map((section, sectionIndex) => <section className="lesson-section" key={`${lesson.id}-${sectionIndex}`}><h3><span className="section-count">{String(sectionIndex + 1).padStart(2, '0')}</span>{section.title}</h3><div className="lesson-prose">{section.body.map((paragraph, i) => <p key={i}><RichText text={paragraph} definitions /></p>)}</div>{section.visual && <LessonVisual kind={section.visual} />}{section.math && <div className="standalone-math"><MathText value={section.math} block /></div>}
      {section.example && <div className="worked-example"><div className="example-label"><PencilLine size={14} /> {say('STAP VOOR STAP', 'LET’S WALK THROUGH IT')}</div><p className="example-prompt"><RichText text={section.example.prompt} definitions /></p><ol className="worked-steps">{section.example.steps.map((step, i) => <li key={i}><span className="step-number">{i + 1}</span><MathText value={step.math} /><span className="step-reason"><RichText text={step.reason} definitions /></span></li>)}</ol>{section.example.check && <div className="example-check"><CheckCircle2 size={17} /><span><RichText text={section.example.check} definitions /></span></div>}</div>}
      {/* Comparing valid methods is informed by Rittle-Johnson & Star (2009),
          https://doi.org/10.1037/a0014224. This interface is our own synthesis. */}
      {section.comparison && <div className="comparison"><div className="example-label">{say('TWEE MANIEREN, DEZELFDE UITKOMST.', 'TWO WAYS. THE SAME ANSWER.')}</div><div className="comparison-columns">{[section.comparison.left, section.comparison.right].map((method, methodIndex) => <div className="comparison-method" key={methodIndex}><span className="method-letter">{methodIndex ? 'B' : 'A'}</span><h4>{method.title}</h4><ol>{method.steps.map((step, stepIndex) => <li key={stepIndex}><RichText text={step} definitions /></li>)}</ol></div>)}</div><p className="comparison-question"><Lightbulb size={16} /> {say('Welke manier vind jij hier eenvoudiger? Waarom krijg je met beide manieren dezelfde oplossing?', 'Which way feels simpler here? Why do both ways give the same answer?')}</p></div>}
      <SourcesNote tags={section.sourceTags} sources={sources} />
      {sectionIndex === 0 && <WordPreview ids={lesson.words || []} />}
    </section>)}
    <section className="checkpoint"><div className="checkpoint-header"><span className="checkpoint-icon"><Lightbulb size={21} /></span><div><span className="eyebrow">{say('EVEN PROBEREN', 'A SMALL CHECK-IN')}</span><h3>{say('Begrijp je het idee?', 'Does the idea click?')}</h3></div></div><p className="checkpoint-prompt"><RichText text={lesson.checkpoint.prompt} definitions /></p><fieldset className="checkpoint-options"><legend className="sr-only">{say('Kies je antwoord', 'Choose your checkpoint answer')}</legend>{lesson.checkpoint.options.map((option, i) => <label key={i} className={`checkpoint-option ${selected === i ? 'selected' : ''} ${checked && selected === i ? correct ? 'right' : 'wrong' : ''}`}><input name={`checkpoint-${lesson.id}`} type="radio" checked={selected === i} onChange={() => { setSelected(i); setChecked(false); }} /><span><RichText text={option} /></span>{checked && selected === i && correct && <Check size={18} />}</label>)}</fieldset><button className="button secondary" disabled={selected === null || checked} onClick={() => setChecked(true)}>{say('Controleer mijn antwoord', 'Check my understanding')} <ArrowRight size={16} /></button>{checked && <div className={`checkpoint-feedback ${correct ? 'correct' : ''}`} role="status"><strong>{correct ? say('Ja, dat is het idee.', 'Yes—that’s the connection.') : say('Nog niet helemaal. Bekijk de uitleg.', 'Not quite. Let’s look at the reasoning.')}</strong><p><RichText text={lesson.checkpoint.explanation} definitions /></p>{!correct && <span>{say('Kies een ander antwoord als je er klaar voor bent.', 'Choose another answer when you’re ready.')}</span>}</div>}</section>
    <SourcesNote tags={lesson.sourceTags} sources={sources} />
    <div className="lesson-end"><div><span className="eyebrow">{say('EEN STAP VERDER', 'ONE STEP FURTHER')}</span><h3>{completed ? say('Dit idee heb je al geoefend.', 'This idea is part of your toolkit.') : say('Klaar voor de volgende stap?', 'Ready to take the next step?')}</h3><p>{completed ? say('Je kunt deze les altijd opnieuw bekijken.', 'You can revisit any lesson, any time.') : say('Beantwoord de controlevraag goed om deze les af te ronden.', 'Answer the check-in correctly to mark this lesson complete.')}</p></div><div className="lesson-end-actions">{!completed && <button className="button primary" disabled={!canComplete} onClick={onComplete}>{say('Les afronden', 'Mark lesson complete')} <Check size={17} /></button>}{completed && <a className="button primary" href={nextHref}>{next ? say('Volgende les', 'Next lesson') : lesson.topic === 'equations' ? say('Ontdek logaritmen', 'Explore logarithms') : say('Oefen met uitleg', 'Try guided practice')}<ArrowRight size={17} /></a>}{!completed && <a className="text-button" href={nextHref}>{say('Bekijk de volgende les', 'Explore the next lesson')} <ArrowRight size={14} /></a>}</div></div>
    <a href="#home" className="inline-link back-link"><ArrowLeft size={15} /> {say('Terug naar je leerroute', 'Back to your learning path')}</a>
  </article>;
}
